### ISSUE TITLE
Adjust volumes in loadbalancing demo

### ISSUE THREAD

**Issue by whatever4711** [hypriot/rpi-cluster-demo#1]
In the target `consultemplate` adjust the external mountpoint `~/docker_arm` and upload the corresponding file to github.

```yml
consultemplate:
  image: hypriot/rpi-consul-template:0.11.0
  restart: always
  volumes:
    - ~/docker_arm:/usr/local/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock
    - ./haproxy/:/haproxy/
  command: -consul 192.168.200.1:8500 -template "/haproxy/haproxy.ctmpl:/haproxy/haproxy.cfg:docker exec infrastructure_haproxy_1 /haproxy-start reload"enter code here
```

Can we get it working from the outside by defining `--env="constraint:node==<hostname of RPi>"` in the compose file, instead of starting the demo only on the master node?
